// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace BEAVRApp
{

public enum Command : byte
{
  resume = 0,
  pause = 1,
  reset = 2,
  home = 3,
};


}
