// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace BEAVRApp
{

public enum HandSide : byte
{
  right = 0,
  left = 1,
  bimanual = 2,
};


}
