// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace BEAVRApp
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct HandData : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_9_23(); }
  public static HandData GetRootAsHandData(ByteBuffer _bb) { return GetRootAsHandData(_bb, new HandData()); }
  public static HandData GetRootAsHandData(ByteBuffer _bb, HandData obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool VerifyHandData(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("", false, HandDataVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public HandData __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public BEAVRApp.TrackingMode Mode { get { int o = __p.__offset(4); return o != 0 ? (BEAVRApp.TrackingMode)__p.bb.GetSbyte(o + __p.bb_pos) : BEAVRApp.TrackingMode.Absolute; } }
  public float Keypoints(int j) { int o = __p.__offset(6); return o != 0 ? __p.bb.GetFloat(__p.__vector(o) + j * 4) : (float)0; }
  public int KeypointsLength { get { int o = __p.__offset(6); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<float> GetKeypointsBytes() { return __p.__vector_as_span<float>(6, 4); }
#else
  public ArraySegment<byte>? GetKeypointsBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public float[] GetKeypointsArray() { return __p.__vector_as_array<float>(6); }

  public static Offset<BEAVRApp.HandData> CreateHandData(FlatBufferBuilder builder,
      BEAVRApp.TrackingMode mode = BEAVRApp.TrackingMode.Absolute,
      VectorOffset keypointsOffset = default(VectorOffset)) {
    builder.StartTable(2);
    HandData.AddKeypoints(builder, keypointsOffset);
    HandData.AddMode(builder, mode);
    return HandData.EndHandData(builder);
  }

  public static void StartHandData(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddMode(FlatBufferBuilder builder, BEAVRApp.TrackingMode mode) { builder.AddSbyte(0, (sbyte)mode, 0); }
  public static void AddKeypoints(FlatBufferBuilder builder, VectorOffset keypointsOffset) { builder.AddOffset(1, keypointsOffset.Value, 0); }
  public static VectorOffset CreateKeypointsVector(FlatBufferBuilder builder, float[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddFloat(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateKeypointsVectorBlock(FlatBufferBuilder builder, float[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateKeypointsVectorBlock(FlatBufferBuilder builder, ArraySegment<float> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateKeypointsVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<float>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartKeypointsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<BEAVRApp.HandData> EndHandData(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<BEAVRApp.HandData>(o);
  }
  public static void FinishHandDataBuffer(FlatBufferBuilder builder, Offset<BEAVRApp.HandData> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedHandDataBuffer(FlatBufferBuilder builder, Offset<BEAVRApp.HandData> offset) { builder.FinishSizePrefixed(offset.Value); }
}


static public class HandDataVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Mode*/, 1 /*BEAVRApp.TrackingMode*/, 1, false)
      && verifier.VerifyVectorOfData(tablePos, 6 /*Keypoints*/, 4 /*float*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
