// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace BEAVRApp
{

public enum IsRelative : byte
{
  relative = 0,
  absolute = 1,
};


}
