// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace BEAVRApp
{

public enum TrackingMode : sbyte
{
  Absolute = 0,
  Relative = 1,
};


}
