// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace BEAVRApp
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct VRInput : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_9_23(); }
  public static VRInput GetRootAsVRInput(ByteBuffer _bb) { return GetRootAsVRInput(_bb, new VRInput()); }
  public static VRInput GetRootAsVRInput(ByteBuffer _bb, VRInput obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool VerifyVRInput(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("", false, VRInputVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public VRInput __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public float Keypoints(int j) { int o = __p.__offset(4); return o != 0 ? __p.bb.GetFloat(__p.__vector(o) + j * 4) : (float)0; }
  public int KeypointsLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<float> GetKeypointsBytes() { return __p.__vector_as_span<float>(4, 4); }
#else
  public ArraySegment<byte>? GetKeypointsBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public float[] GetKeypointsArray() { return __p.__vector_as_array<float>(4); }
  public BEAVRApp.HandSide HandSide { get { int o = __p.__offset(6); return o != 0 ? (BEAVRApp.HandSide)__p.bb.Get(o + __p.bb_pos) : BEAVRApp.HandSide.right; } }
  public BEAVRApp.IsRelative IsRelative { get { int o = __p.__offset(8); return o != 0 ? (BEAVRApp.IsRelative)__p.bb.Get(o + __p.bb_pos) : BEAVRApp.IsRelative.relative; } }
  public BEAVRApp.Command Command { get { int o = __p.__offset(10); return o != 0 ? (BEAVRApp.Command)__p.bb.Get(o + __p.bb_pos) : BEAVRApp.Command.resume; } }

  public static Offset<BEAVRApp.VRInput> CreateVRInput(FlatBufferBuilder builder,
      VectorOffset keypointsOffset = default(VectorOffset),
      BEAVRApp.HandSide hand_side = BEAVRApp.HandSide.right,
      BEAVRApp.IsRelative is_relative = BEAVRApp.IsRelative.relative,
      BEAVRApp.Command command = BEAVRApp.Command.resume) {
    builder.StartTable(4);
    VRInput.AddKeypoints(builder, keypointsOffset);
    VRInput.AddCommand(builder, command);
    VRInput.AddIsRelative(builder, is_relative);
    VRInput.AddHandSide(builder, hand_side);
    return VRInput.EndVRInput(builder);
  }

  public static void StartVRInput(FlatBufferBuilder builder) { builder.StartTable(4); }
  public static void AddKeypoints(FlatBufferBuilder builder, VectorOffset keypointsOffset) { builder.AddOffset(0, keypointsOffset.Value, 0); }
  public static VectorOffset CreateKeypointsVector(FlatBufferBuilder builder, float[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddFloat(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateKeypointsVectorBlock(FlatBufferBuilder builder, float[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateKeypointsVectorBlock(FlatBufferBuilder builder, ArraySegment<float> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateKeypointsVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<float>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartKeypointsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddHandSide(FlatBufferBuilder builder, BEAVRApp.HandSide handSide) { builder.AddByte(1, (byte)handSide, 0); }
  public static void AddIsRelative(FlatBufferBuilder builder, BEAVRApp.IsRelative isRelative) { builder.AddByte(2, (byte)isRelative, 0); }
  public static void AddCommand(FlatBufferBuilder builder, BEAVRApp.Command command) { builder.AddByte(3, (byte)command, 0); }
  public static Offset<BEAVRApp.VRInput> EndVRInput(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<BEAVRApp.VRInput>(o);
  }
  public static void FinishVRInputBuffer(FlatBufferBuilder builder, Offset<BEAVRApp.VRInput> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedVRInputBuffer(FlatBufferBuilder builder, Offset<BEAVRApp.VRInput> offset) { builder.FinishSizePrefixed(offset.Value); }
}


static public class VRInputVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyVectorOfData(tablePos, 4 /*Keypoints*/, 4 /*float*/, false)
      && verifier.VerifyField(tablePos, 6 /*HandSide*/, 1 /*BEAVRApp.HandSide*/, 1, false)
      && verifier.VerifyField(tablePos, 8 /*IsRelative*/, 1 /*BEAVRApp.IsRelative*/, 1, false)
      && verifier.VerifyField(tablePos, 10 /*Command*/, 1 /*BEAVRApp.Command*/, 1, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
